/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/help/1': RouteRecordInfo<'/help/1', '/help/1', Record<never, never>, Record<never, never>>,
    '/nav/0': RouteRecordInfo<'/nav/0', '/nav/0', Record<never, never>, Record<never, never>>,
    '/nav/0_components/AppAdd': RouteRecordInfo<'/nav/0_components/AppAdd', '/nav/0_components/AppAdd', Record<never, never>, Record<never, never>>,
    '/nav/0_components/AppEditor': RouteRecordInfo<'/nav/0_components/AppEditor', '/nav/0_components/AppEditor', Record<never, never>, Record<never, never>>,
    '/nav/0_components/AppList': RouteRecordInfo<'/nav/0_components/AppList', '/nav/0_components/AppList', Record<never, never>, Record<never, never>>,
    '/nav/1': RouteRecordInfo<'/nav/1', '/nav/1', Record<never, never>, Record<never, never>>,
    '/nav/1/item-1': RouteRecordInfo<'/nav/1/item-1', '/nav/1/item-1', Record<never, never>, Record<never, never>>,
    '/nav/1_components/ChartComponent': RouteRecordInfo<'/nav/1_components/ChartComponent', '/nav/1_components/ChartComponent', Record<never, never>, Record<never, never>>,
    '/nav/1_components/FormComponent': RouteRecordInfo<'/nav/1_components/FormComponent', '/nav/1_components/FormComponent', Record<never, never>, Record<never, never>>,
    '/nav/1_components/TableDataList': RouteRecordInfo<'/nav/1_components/TableDataList', '/nav/1_components/TableDataList', Record<never, never>, Record<never, never>>,
    '/nav/1_components/TableDevList': RouteRecordInfo<'/nav/1_components/TableDevList', '/nav/1_components/TableDevList', Record<never, never>, Record<never, never>>,
    '/nav/2': RouteRecordInfo<'/nav/2', '/nav/2', Record<never, never>, Record<never, never>>,
    '/nav/4': RouteRecordInfo<'/nav/4', '/nav/4', Record<never, never>, Record<never, never>>,
    '/nav/5': RouteRecordInfo<'/nav/5', '/nav/5', Record<never, never>, Record<never, never>>,
  }
}
